apiVersion: v1
kind: Namespace
metadata:
  name: myresume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-myresume
  namespace: myresume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myresume
  template:
    metadata:
      labels:
        app: myresume
    spec:
      containers:
      - name: myresume
        image: derrickwoolworth/nginx-resume:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-myresume-svc
  namespace: myresume
spec:
  selector:
    app: myresume
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
